name = "share-toilet"
compatibility_date = "2024-12-06"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "share-toilet-db"
database_id = "9c8612ca-810e-4fa1-8c0b-057951f7fb6d"

[site]
bucket = "./dist"

[build]
command = "npm run build"
